### ISSUE TITLE
Problem with the cell "Sum personmonths (full time+part time)"

### ISSUE THREAD

**Issue by natlio** [isa-group/wecaremed#17]
In the section "Partners" when I modify the values in the cell "Sum personmonths (full time+part time) the results (fuels-heat, electricity, water) remain the same.
Also, I tried to create a new project and filled in with values the specific cell and no CF was calculated for the corresponding sources.

**Comment by MaToSan24** [comment]
We were aware of this issue and we've been trying to solve it. I think that I have already fixed it so feel free to try and check the app again. Make sure that you create new partners in order for the app to work, because the partners that already exist on the app are outdated and will make the app crash if you keep them in a project.

**Comment by natlio** [comment]
Thank you. But it seems that the problem remains. I tried by creating a new project.

**Comment by MaToSan24** [comment]
You're right, I think I've finally fixed it, the problem had to do with something completely different this time. I have been able to calculate the CF in your project successfully: 
![image](https://user-images.githubusercontent.com/63660411/154712173-f4a2f3fc-282c-4df4-aae6-b256f078f51b.png)

**Comment by natlio** [comment]
Thank you very much!It works fine!

**Comment by spapadog** [comment]
Τhe problem, as mentioned above, remains today.

**Comment by MaToSan24** [comment]
Try to give some information in order to reproduce your problem please. For me, it works fine, and Natalia said that it works for her too. Have you deleted the old partners and created new ones? 

> We were aware of this issue and we've been trying to solve it. I think that I have already fixed it so feel free to try and check the app again. Make sure that you create new partners in order for the app to work, because the partners that already exist on the app are outdated and will make the app crash if you keep them in a project.

**Comment by spapadog** [comment]
Yes, I have deleted all old partners, I create new ones and when I calculate total tons the responce is:
![wecaremed](https://user-images.githubusercontent.com/79985199/154930396-60617a44-02e1-4de8-a32e-76012fcd3331.png)

**Comment by natlio** [comment]
Indeed, I have the same problem again even though it was working on Friday.

**Comment by MaToSan24** [comment]
It should be working again, I will try to find out why the app stops working suddenly from time to time.

**Comment by natlio** [comment]
Please let me know when the problem is fixed. I just noticed that the same occurs with events participated by the project where I change the values (number of events, participants) and the result remains the same. Thanks

**Comment by MaToSan24** [comment]
It works for me now. The problem is that some data from the app database is dissapearing randomly after some time even if we dont modify the app's code. We need to investigate this issue.

**Comment by ARPAV2022** [comment]
> Please let me know when the problem is fixed. I just noticed that the same occurs with events participated by the project where I change the values (number of events, participants) and the result remains the same. Thanks

We noticed the same problem. we changed from 2 to 20000 participants, but the CF remains unchanged

<img width="934" alt="Immagine 2022-02-24 163718" src="https://user-images.githubusercontent.com/98102967/155723778-a3c7f034-b674-40e0-94c5-b802af0ccd29.png">

<img width="944" alt="Immagine 2022-02-25 143423" src="https://user-images.githubusercontent.com/98102967/155724129-8d752b0b-3e48-4b15-a8e9-99ae64cd1d78.png">

**Comment by MaToSan24** [comment]
> > Please let me know when the problem is fixed. I just noticed that the same occurs with events participated by the project where I change the values (number of events, participants) and the result remains the same. Thanks
> 
> We noticed the same problem. we changed from 2 to 20000 participants, but the CF remains unchanged
> 
> <img alt="Immagine 2022-02-24 163718" width="934" src="https://user-images.githubusercontent.com/98102967/155723778-a3c7f034-b674-40e0-94c5-b802af0ccd29.png">
> 
> <img alt="Immagine 2022-02-25 143423" width="944" src="https://user-images.githubusercontent.com/98102967/155724129-8d752b0b-3e48-4b15-a8e9-99ae64cd1d78.png">

This is happening because there are some partners that don't have a value in some of their fields. In this case, the field "sum person months (full time + part time)" does not have any value set so, the calculations can't be made. I've made sure that an error pops up when this scenario happens:

![image](https://user-images.githubusercontent.com/63660411/155826814-45beb66c-b3cc-4d7b-90c9-aaeb8fe59e21.png)
![image](https://user-images.githubusercontent.com/63660411/155826817-2c6a61b6-c2a0-4388-a83e-ffdf3fad3705.png)
![image](https://user-images.githubusercontent.com/63660411/155826839-29bea060-03e1-441b-9ec7-deefdbd7e4f1.png)

**Comment by ARPAV2022** [comment]
you're right. I have inserted the missing values on personmonth column and now the CF values vary also according to the number of participants.  Thank you
I think it is important to highlight (in the way you suggested) the values that cannot be blank, in order to have consistent results.
It seems that also the overall CF value for "Events" is more reasonable and comparable with CF of other breakdown processes. From our side this issue can be closed.  Thank you again.
